<?php

/**
 * @file
 * Contains ui_patterns.module.
 */

/**
 * Implements hook_theme().
 */
function ui_patterns_theme() {
  return [
    'patterns_overview_page' => [
      'variables' => ['patterns' => NULL],
    ],
    'patterns_single_page' => [
      'variables' => ['pattern' => NULL],
    ],
    'patterns_meta_information' => [
      'variables' => ['pattern' => NULL],
    ],
  ] + \Drupal::service('plugin.manager.ui_patterns')->hookTheme();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter()
 */
function ui_patterns_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if (\Drupal::service('plugin.manager.ui_patterns')->isPatternHook($hook) && !empty($variables['context'])) {
    \Drupal::service('module_handler')->alter('ui_patterns_suggestions', $suggestions, $variables, $variables['context']);
  }
}
