<?php

/**
 * @file
 * Contains ui_patterns.module.
 */

/**
 * Implements hook_theme().
 */
function ui_patterns_test_theme() {
  return [
    'patterns_test_page' => [
      'variables' => ['patterns' => NULL],
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function ui_patterns_test_library_info_alter(&$libraries, $extension) {
  if ($extension === 'ui_patterns') {
    $libraries['media.library_two']['css']['theme']['/'. drupal_get_path('theme', 'ui_patterns_test_theme') . '/templates/patterns/media/css/media2-1.css'] = [];
    $libraries['media.library_three']['css']['theme']['/'. drupal_get_path('theme', 'ui_patterns_test_theme') . '/templates/patterns/media/css/media3.css'] = [];
  }
}
