<?php

/**
 * @file
 * Contains module file.
 */

/**
 * Implements hook_theme().
 */
function ui_patterns_library_theme() {
  return [
    'patterns_overview_page' => [
      'variables' => ['patterns' => NULL],
    ],
    'patterns_single_page' => [
      'variables' => ['pattern' => NULL],
    ],
    'patterns_meta_information' => [
      'variables' => ['pattern' => NULL],
    ],
    'patterns_variant_meta_information' => [
      'variables' => ['variant' => NULL],
    ],
  ];
}
