<?php

/**
 * @file
 * Contains module file.
 */

use Drupal\Core\Layout\LayoutDefinition;

/**
 * Implements hook_layout_alter().
 */
function ui_patterns_layouts_layout_alter(&$definitions) {
  /** @var \Drupal\sdc\ComponentPluginManager $plugin_manager */
  $plugin_manager = \Drupal::service('plugin.manager.sdc');
  /** @var \Drupal\sdc\Component\ComponentMetadata[] $components */
  $components = $plugin_manager->getDefinitions();
  foreach ($components as $component) {
    $definition = [
      'label' => $component['name'] ?? $component['id'],
      'category' => 'sdc',
      'provider' => $component['provider'],
      'class' => '\Drupal\ui_patterns_layouts\Plugin\Layout\PatternLayout',
      'id' => $component['id'],
    ];
    if (isset($component['slots'])) {
      foreach ($component['slots'] as $slot_id => $slot) {
        $definition['regions'][$slot_id]['label'] = $slot['title'];
      }
    }

    $definitions[str_replace('-', '_', $component['id'])] = new LayoutDefinition($definition);
  }
}
