<?php

/**
 * @file
 * Contains ui_patterns_props_widget.module.
 */

use Drupal\ui_patterns_props_widget\Form\PropsWidgetFormBuilder;
use Drupal\sdc\Component\ComponentMetadata;

/**
 * Implements hook_ui_patterns_layouts_display_configuration_form_alte().
 */
function ui_patterns_props_widget_ui_patterns_layouts_display_configuration_form_alter(&$form, ComponentMetadata $component_metadata, $configuration) {
  PropsWidgetFormBuilder::layoutForm($form, $component_metadata, $configuration);
}

/**
 * Implements hook_element_info_alter().
 */
function ui_patterns_props_widget_element_info_alter(array &$info) {
  if (isset($info['component'])) {
    array_unshift($info['component']['#pre_render'], [
      "Drupal\ui_patterns_props_widget\Element\ComponentPropsWidget",
      "processPropsWidget",
    ]);
  }

}
